typography_spectrum: 0.3468920812010765
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.29836400342173874
  lightness: 0.4379361055325717
  saturation: 0.9103390630334616
  rhythmicContrast: 0.26394371315836906
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.31654473720118403
analytics:
  google: null
  facebook: null
  twitter: null
name: Leslie Bishop
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Employee Morale Specialist
purpose: []
